/* actions/main.js */
$('.date').datepicker({format:"yyyy/mm/dd",todayBtn:"linked",viewMode:"years",autoclose:true,todayHighlight:true,orientation:"top"});$('#submit-login').click(function(){var settings=[];settings['url']='http://localhost:8765/users/login';settings['type']='post';settings['data']=$('#login-form').serialize();settings['beforeSend']='';settings['success']=function(response){displayMessage('#login_modal','.message',response);}
settings['error']=function(XMLHttpRequest,textStatus,errorThrown){defaultAjaxErrorHandler(XMLHttpRequest,textStatus,errorThrown);}
settings['dataType']='json';settings['global']=false;functionAjax(settings);});function displayMessage(parentId,messageLocal,response){printMessage(parentId,messageLocal,response);styleMessage(parentId,messageLocal,response);if(response['type']==='Sucesso'){location.reload();}}
function printMessage(parentId,messageLocal,response){var message='';for(var item in response){if(response[item]!=null){message+=response[item]+' - ';}}
$(parentId+' '+messageLocal).text(message.slice(0,-3));}
function styleMessage(parentId,messageLocal,response){if(response['type']==='Erro'){$(parentId+' '+messageLocal).addClass('error');$(parentId+' '+messageLocal).removeClass('success');$(parentId+' '+messageLocal).removeClass('warning');}else if(response['type']==='Sucesso'){$(parentId+' '+messageLocal).addClass('success');$(parentId+' '+messageLocal).removeClass('warning');$(parentId+' '+messageLocal).removeClass('error');}else if(response['type']==='Cuidado'){$(parentId+' '+messageLocal).addClass('warning');$(parentId+' '+messageLocal).removeClass('error');$(parentId+' '+messageLocal).removeClass('success');}}
function deleteAccount(url){var settings=[];settings['url']=url;settings['type']='post';settings['data']='';settings['beforeSend']='';settings['success']=function(response){displayMessage('#delete_account_modal','.message',response);}
settings['error']=function(XMLHttpRequest,textStatus,errorThrown){defaultAjaxErrorHandler(XMLHttpRequest,textStatus,errorThrown);}
settings['dataType']='json';settings['global']=false;functionAjax(settings);}
function editAccount(url){var settings=[];settings['url']=url;settings['type']='post';settings['data']=$('#edit-profile-form').serialize();settings['beforeSend']='';settings['success']=function(response){displayMessage('#edit_profile_modal','.message',response);}
settings['error']=function(XMLHttpRequest,textStatus,errorThrown){defaultAjaxErrorHandler(XMLHttpRequest,textStatus,errorThrown);}
settings['dataType']='json';settings['global']=false;functionAjax(settings);}
$('#submit-crete-account').click(function(){var settings=[];settings['url']='http://localhost:8765/users/add';settings['type']='post';settings['data']=$('#create-account-form').serialize();settings['beforeSend']='';settings['success']=function(response){displayMessage('#create_account_modal','.message',response);}
settings['error']=function(XMLHttpRequest,textStatus,errorThrown){defaultAjaxErrorHandler(XMLHttpRequest,textStatus,errorThrown);}
settings['dataType']='json';settings['global']=false;functionAjax(settings);});$.getJSON("http://localhost:8765/json/products.json",function(products){autoCompleteMulti(products,'#search');});function autoCompleteMulti(words,selector){$(selector).bind("keydown",function(event){if(event.keyCode===$.ui.keyCode.TAB&&$(this).autocomplete("instance").menu.active){event.preventDefault();}}).autocomplete({minLength:2,source:function(request,response){var results=$.ui.autocomplete.filter(words,extractLast(request.term));response(results.slice(0,10));},focus:function(){return false;},select:function(event,ui){var terms=split(this.value);terms.pop();terms.push(ui.item.value);terms.push("");this.value=terms.join(" ");return false;}});}
function split(val){return val.split(/ \s*/);}
function extractLast(term){return split(term).pop();}
$("#password").popover({title:'A senha deve conter entre 8 e 16 caracteres, incluindo:',content:'<ul><li>Letras Maiusculas</li><li>Letras Minusculas</li><li>Numeros</li></ul>',trigger:'hover',placement:'right'});$("#login-form").validate({rules:{email:{required:true,minlength:8},password:"required"},messages:{email:{required:"Please provide your Login",minlength:"Your Login must be at least 8 characters"},pass:"Please provide your password"}});$('#back-top').click(function(){$('html, body').animate({scrollTop:0},'slow');return false;});function redirect(option){location=option.value;}
function defaultAjaxErrorHandler(XMLHttpRequest,textStatus,errorThrown){console.log(XMLHttpRequest);console.log(textStatus);console.log(errorThrown);}
function functionAjax(settings){$.ajax({type:settings['type'],url:settings['url'],data:settings['data'],beforeSend:settings['beforeSend'],success:settings['success'],error:settings['error'],dataType:settings['dataType'],global:settings['global']});}
var productThumbSlider={slideWidth:250,minSlides:1,maxSlides:3,moveSlides:1,auto:false};var viewProductSlider=$("#view-product-modal .product-slider").bxSlider(productThumbSlider);$('#view-product-modal').on('shown.bs.modal',function(e){viewProductSlider.reloadSlider();});$('#edit-store-products .product-slider').bxSlider(productThumbSlider);$('#edit-store .product-slider').bxSlider(productThumbSlider);
/* actions/index-banners.js */
var addBannerModalClicked=false;$('[data-target=#add_banner_modal]').click(function(){if(addBannerModalClicked===false){$.getJSON("http://localhost:8765/json/countries.json",function(countries){for(var i=0;i<countries.length;i++){$('.country').append('<option value=\"'+countries[i].code+'\">'+countries[i].name+'</option>');}});addBannerModalClicked=true;}});function viewBanner(url){var settings=[];settings['url']=url;settings['type']='get';settings['data']='';settings['beforeSend']='';settings['success']=function(response){formatViewSmallFullBanner(response);formatViewBanner(response);}
settings['error']=function(XMLHttpRequest,textStatus,errorThrown){defaultAjaxErrorHandler(XMLHttpRequest,textStatus,errorThrown);}
settings['dataType']='json';settings['global']=false;functionAjax(settings);}
function formatViewSmallFullBanner(banner){if(banner.banner_type_id===1){$('#banner-pic-modal').addClass('picture-left');$('#banner-info').addClass('banner-information');}else if(banner.banner_type_id===2){$('#banner-pic-modal').removeClass('picture-left');$('#banner-info').removeClass('banner-information');$('#banner-pic-modal').css('max-width','100%');}}
function formatViewBanner(banner){$('#banner-name-modal').text(banner.banner_description);$('#banner-pic-modal').attr('src',banner.path_banner);$('#banner-id-modal').text(banner.id);$('#banner-type-modal').text(banner.banner_type_id);$('#banner-url-redirect-modal').text(banner.url_redirect);$('#banner-created-modal').text(banner.created);$('#banner-modified-modal').text(banner.modified);$('#banner-description-modal').text(banner.banner_description);}
function editBanner(url){var settings=[];settings['url']=url;settings['type']='get';settings['data']='';settings['beforeSend']='';settings['success']=function(response){formatEditSmallFullBanner(response);formatEditBanner(response);}
settings['error']=function(XMLHttpRequest,textStatus,errorThrown){defaultAjaxErrorHandler(XMLHttpRequest,textStatus,errorThrown);}
settings['dataType']='json';settings['global']=false;functionAjax(settings);}
function formatEditSmallFullBanner(banner){if(banner.banner_type_id===1){$('#banner-pic-modal').addClass('picture-left');}else if(banner.banner_type_id===2){$('#banner-pic-modal').removeClass('picture-left');$('#banner-pic-modal').css('max-width','100%');}}
function formatEditBanner(banner){$('#banner-pic-edit-modal').attr('src','/img/'+banner.path_banner);$('#link-edit').attr('value',banner.url_redirect);$('#title-edit').attr('value',banner.banner_description);}
/* actions/upload-products.js */
Dropzone.autoDiscover=false;var addProductDropzone=new Dropzone('#addProductDropzone',{url:'http://localhost:8765/products/upload',autoProcessQueue:false,uploadMultiple:true,parallelUploads:100,maxFiles:3,previewsContainer:".dropzone-previews"});$("#submit-all").click(function(e){addProductDropzone.on("sending",function(file,xhr,formData){alert('submit');var fieldsAssociativeArray=getComplementedFields('#add-products-complement :input');fieldsAssociativeArray=fieldsAssociativeArray.concat(getComplementedFields('#add-products-properties :input'));appendAllFieldsToDropzone(formData,fieldsAssociativeArray);});addProductDropzone.processQueue();});function getComplementedFields(fieldId){var fieldsAssociativeArray=[];$(fieldId).each(function(){if(['INPUT','SELECT','TEXTAREA'].indexOf($(this).context.tagName)>=0){fieldsAssociativeArray.push({name:$(this).context.name,value:$(this).context.value});}});return fieldsAssociativeArray;}
function appendAllFieldsToDropzone(formData,fields){for(var i in fields){formData.append(fields[i]['name'],fields[i]['value']);}}
var productsFeatures='';var addProductClicked=false;$('#add-product-button').click(function(){if(addProductClicked===false){addProductClicked=true;var settings=[];settings['url']='/json/features.json';settings['callback']=function(data){productsFeatures=data;appendFeatureOptions('#feature-insert',data);}
getJsonDownload(settings);}});function appendFeatureOptions(fieldID,data){for(var i=0;i<data.length;i++){$(fieldID).append('<option value=\"'+data[i].id+'\">'+data[i].label+'</option>');}}
function getJsonDownload(settings){$.getJSON(settings['url'],settings['callback']);}
$('#insert-feature-button').click(function(){var id=$('#feature-insert').val();addFeatureInModal(id);removeFeatureOption('#feature-insert option[value="'+id+'"]');});function addFeatureInModal(fieldID){for(var i=0;i<productsFeatures.length;i++){if(productsFeatures[i].id==fieldID){var element=createFeatureElent(productsFeatures[i]);appendFeatureContainer(productsFeatures[i],element,'#features-container');break;}}}
function removeFeatureOption(field){$(field).remove();}
function createFeatureElent(field){var element=document.createElement(field.tag);var excludedAtributtes=['tag','label'];for(var key in field){if(excludedAtributtes.indexOf(key)<0){$(element).attr(key,field[key]);}}
$(element).addClass('form-control');return element;}
function appendFeatureContainer(field,element,parentID){var spanRemove=document.createElement('span');$(spanRemove).addClass('glyphicon glyphicon-remove');var remove=document.createElement('button');$(remove).addClass('btn btn-danger remove-button');$(remove).append(spanRemove);var elementContainer=document.createElement('div');$(elementContainer).addClass('col-md-6');$(elementContainer).append(element);$(elementContainer).append(remove);var label=document.createElement('label');$(label).attr('for',field.id);$(label).addClass('col-md-3 col-md-offset-1 control-label');$(label).append(field.label);var div=document.createElement('div');$(div).addClass('form-group row');$(div).append(label);$(div).append(elementContainer);$(parentID).append(div);}
$('#reset-all').click(function(){emptyContainer('#features-container');emptyContainer('#feature-insert');appendFeatureOptions('#feature-insert',productsFeatures);});function emptyContainer(containerID){$(containerID).empty();}
$('#features-container').on('click','.remove-button',function(){var featureID=$(this).parent().parent().find('input').attr('id');$(this).parent().parent().remove();var productFeature=findFeatureById(productsFeatures,featureID);reInsertFeatureOption('#feature-insert',productFeature);});function findFeatureById(productsFeatures,id){for(var i=0;i<productsFeatures.length;i++){if(productsFeatures[i].id==id){return productsFeatures[i];}}}
function reInsertFeatureOption(selectID,data){$(selectID).append('<option value=\"'+data.id+'\">'+data.label+'</option>');}
